on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  ldoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y luarocks
          sudo luarocks install ldoc

      - name: Create docs
        run: ldoc .

      - name: Push docs to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: doc
